In [0]:
import torch
import numpy as np 

In [55]:
print(torch.__version__)

1.1.0


In [56]:
torch.cuda.is_available()

True

In [57]:
torch.version.cuda

'10.0.130'

# Using CUDA

In [58]:
t = torch.tensor([1, 2, 3])
t

tensor([1, 2, 3])

In [59]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

# Indexes

In [0]:
a = [1, 2, 3, 4]  # Rank 1 tensor 

In [61]:
a[2]

3

In [0]:
dd =  [         # Rank 2 tensor
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [63]:
dd

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [64]:
dd[0][2]

3

# Shape / Size of tensor 

In [0]:
dd =  [         # Rank 2 tensor
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [66]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
type(t)

torch.Tensor

In [68]:
t.shape

torch.Size([3, 3])

In [69]:
t.reshape(1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
t.reshape(1, 9).shape

torch.Size([1, 9])

# Tensor Class 

In [71]:
# Tensors in Pytorch are represented using the torch.Tensor class.

t = torch.Tensor()
type(t)

torch.Tensor

# Tensor Attributes

In [72]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [73]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

# Creation options using data

In [74]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [0]:
# Tensor computations dempend on the device and the type
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1., 2., 3.])

In [76]:
t1.dtype

torch.int64

In [77]:
t2.dtype

torch.float32

In [78]:
t1 + t2

RuntimeError: ignored

# GPU Value vs CPU Value

In [0]:
t1 = torch.tensor([1, 2, 3])
t2 = t1.cuda()                  # Same variable but converted to device

In [80]:
t1.device

device(type='cpu')

In [81]:
t2.device

device(type='cuda', index=0)

In [82]:
t1 + t2

RuntimeError: ignored

# Createing options using data numpy array data to tensor

In [83]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [84]:
d1 = torch.Tensor(data)  ## nummpy => Tensor  = Float tensor
print(d1)
d1.dtype

tensor([1., 2., 3.])


torch.float32

In [85]:
d2 = torch.tensor(data)  # np => tensor = int tensor
print(d2)
d2.dtype

tensor([1, 2, 3])


torch.int64

In [86]:
d3 = torch.as_tensor(data) # np => as_tensor = int tensor
print(d3)
d3.dtype

tensor([1, 2, 3])


torch.int64

In [87]:
d4 = torch.from_numpy(data) # np => from_numpy = int tensor
print(d4)
d4.dtype

tensor([1, 2, 3])


torch.int64

# Cration options without data

In [88]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [89]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [90]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [91]:
torch.zeros(2, 2)    # Create 0 filled array

tensor([[0., 0.],
        [0., 0.]])

In [92]:
torch.ones(2, 2)    # Create 1 filed array

tensor([[1., 1.],
        [1., 1.]])

In [93]:
torch.rand(2, 2)  # Create randed filled array

tensor([[0.1488, 0.0205],
        [0.1842, 0.1154]])

In [94]:
# tensor types
torch.get_default_dtype() # default torch value type

torch.float32

In [95]:
t1 = torch.tensor(np.array([1, 2, 3])) # Int => Int out
print(t1)
t1.dtype

tensor([1, 2, 3])


torch.int64

In [96]:
t2 = torch.tensor(np.array([1., 2., 3.]))  # Float => float out
print(t2)
t2.dtype

tensor([1., 2., 3.], dtype=torch.float64)


torch.float64

In [97]:
t3 = torch.tensor(np.array([1, 2, 3]), dtype=torch.float64) # int conver to float
print(t2)
t2.dtype

tensor([1., 2., 3.], dtype=torch.float64)


torch.float64

# Memroy : Sharing Vs Copying

In [98]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [0]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [0]:
data[0] = 0
data[1] = 0
data[2] = 0


In [101]:
print(t1) # torch.Tensor(data)
print(t2) # torch.tensor(data)

# These method copy data from data so not effect change data variable

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [102]:
print(t3)   # torch.as_tensor(data)  
print(t4)   # torch.from_numpy(data)

# These are share the memotry so that's why it's change when change data update

tensor([0, 0, 0])
tensor([0, 0, 0])


# ReShape

In [0]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3] 
], dtype=torch.float32)

In [104]:
t.size()

torch.Size([3, 4])

In [105]:
t.shape

torch.Size([3, 4])

In [106]:
len(t.shape)

2

In [107]:
torch.tensor(t.shape).prod()

tensor(12)

In [108]:
t.numel()  # multile

12

In [109]:
t.reshape(2, 6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [110]:
t.reshape(6, 2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [111]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [112]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [113]:
t.reshape(2, 2, 3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

# SQUEEZE and unsqueeze

In [0]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3] 
], dtype=torch.float32)

In [115]:
print(t.reshape(1, 12))            # reshape only look at the next example
print(t.reshape(1, 12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [116]:
print(t.reshape(1, 12).squeeze())   # squezee remove all the axis lenth of 1
print(t.reshape(1, 12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [117]:
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0)) # squezee add axis lenth of 1
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [118]:
t.flatten() # pytorch implementation 

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [119]:
t.reshape(1, -1)[0] # other ways to flattern 

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [120]:
t.reshape(-1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [121]:
t.view(t.numel())

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

# CNN - Flatten Operation Visualize

In [0]:
t1 = torch.tensor([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])

t2 = torch.tensor([
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2]
])

t3 = torch.tensor([
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3]
])

In [123]:
t = torch.stack((t1, t2, t3))
t.shape

torch.Size([3, 4, 4])

In [124]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [125]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [126]:
t.flatten(start_dim=0)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [127]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [128]:
t.flatten(start_dim=2)

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

# Math operations

In [0]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9, 8],
    [7, 6]
], dtype=torch.float32)

In [130]:
t1

tensor([[1., 2.],
        [3., 4.]])

In [131]:
t2

tensor([[9., 8.],
        [7., 6.]])

In [132]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [133]:
t1 - t2

tensor([[-8., -6.],
        [-4., -2.]])

In [134]:
t2 - t1

tensor([[8., 6.],
        [4., 2.]])

In [135]:
t2 - t2

tensor([[0., 0.],
        [0., 0.]])

In [136]:
t1 + 1

tensor([[2., 3.],
        [4., 5.]])

In [137]:
t1.add(1)

tensor([[2., 3.],
        [4., 5.]])

In [138]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [139]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [140]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [141]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [142]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [143]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

# Broadcasting

In [144]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [145]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [146]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape),
    dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

# Element vise operations

In [0]:
t1 = torch.tensor([
    [1, 1],
    [1, 1]
], dtype=torch.float32)

t2 = torch.tensor([2, 4], dtype=torch.float32)

In [148]:
t1.shape

torch.Size([2, 2])

In [149]:
t2.shape

torch.Size([2])

In [150]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [151]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [152]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

# Operation

In [0]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [154]:
t.eq(0) # eq = equal to 0 

tensor([[1, 0, 0],
        [0, 1, 0],
        [1, 0, 1]], dtype=torch.uint8)

In [155]:
t.ge(0)  # greater than or equal 0

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [156]:
t.gt(0) # greater than 0

tensor([[0, 1, 1],
        [1, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [157]:
t.lt(0) # less than 0

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [158]:
t.le(7)  # less than or e to 7

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

# Compare with tensor

In [0]:
t = torch.tensor([
    [0, 5, 7],
    [6, 0, 7],
    [0, 8, 0]
], dtype=torch.float32)

In [160]:
npt = np.broadcast_to(7, t.shape)
print(npt)
print('-------------------------------')
t <= torch.tensor(                  # greater than or equal to [7, 7....] array
    np.broadcast_to(7, t.shape),
    dtype=torch.float32
)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
-------------------------------


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

In [161]:
t <= torch.tensor([                 # greater than or equal to [7, 7....] array
    [7, 7, 7],
    [7, 7, 7],
    [7, 7, 7]
], dtype=torch.float32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

# Get abstract , mean of tensor

In [162]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [163]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [164]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [165]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

# Reduction operation


In [0]:
t = torch.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 0]
], dtype=torch.float32)

In [167]:
t.sum()

tensor(8.)

In [168]:
t.numel()

9

In [169]:
t.sum().numel()

1

In [170]:
t.sum().numel() < t.numel()

True

In [171]:
t.mean()

tensor(0.8889)

In [172]:
t.std()

tensor(1.1667)

# Reduction operations

In [0]:
t = torch.tensor([
  [1, 1, 1, 1],
  [2, 2, 2, 2],
  [3, 3, 3, 3]
], dtype=torch.float32)

In [174]:
t.sum()

tensor(24.)

In [175]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [176]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [177]:
t[0]

tensor([1., 1., 1., 1.])

In [178]:
t[1]

tensor([2., 2., 2., 2.])

In [179]:
t[2]

tensor([3., 3., 3., 3.])

In [180]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

In [181]:
t[0].sum()

tensor(4.)

In [182]:
t[1].sum()

tensor(8.)

In [183]:
t[2].sum()

tensor(12.)

In [184]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

# Max - Min - Argmax - Flattern

In [0]:
t = torch.tensor([
    [1, 0, 0, 2],
    [0, 3, 3, 0],
    [4, 0, 0, 5]
], dtype=torch.float32)

In [186]:
t.max()

tensor(5.)

In [187]:
t.min()

tensor(0.)

In [188]:
t.argmax()    # theis 11 index came from after flattern the 2d array 11 th index is the highest values

tensor(11)

In [189]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [190]:
# axis wise max
t.max(dim=0)

torch.return_types.max(values=tensor([4., 3., 3., 5.]), indices=tensor([2, 1, 1, 2]))

In [191]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [192]:
t.max(dim=1)

torch.return_types.max(values=tensor([2., 3., 5.]), indices=tensor([3, 2, 3]))

In [193]:
t.argmax(dim=1)

tensor([3, 2, 3])

In [0]:
t = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=torch.float32)

In [195]:
t.mean()

tensor(5.)

In [196]:
t.mean().item()

5.0

In [197]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [198]:
t.mean(dim=1).tolist()

[2.0, 5.0, 8.0]

In [199]:
t.mean(dim=1).numpy()

array([2., 5., 8.], dtype=float32)